//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneTicketsApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirlineDBsEntities1 : DbContext
    {
        public AirlineDBsEntities1()
            : base("name=AirlineDBsEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AirlineRecord> AirlineRecords { get; set; }
        public virtual DbSet<Classtbl> Classtbls { get; set; }
        public virtual DbSet<DestinationTbl> DestinationTbls { get; set; }
        public virtual DbSet<PassengerTbl> PassengerTbls { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
