//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirplaneTicketsApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DestinationTbl()
        {
            this.PassengerTbls = new HashSet<PassengerTbl>();
        }
    
        public int id { get; set; }
        public string destinationCityName { get; set; }
        public Nullable<int> classId { get; set; }
    
        public virtual Classtbl Classtbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PassengerTbl> PassengerTbls { get; set; }
    }
}
